
# ~/miniconda3/envs/mlp/bin/python3.7 ../src/lowlevel/main.py --phase train --experiment_name ex_5_emnist_64_4 --dataset emnist --gpu_ids 0,1 --feature_layer_size 64 --categorical_dim 4 --num_epochs 200
# ~/miniconda3/envs/mlp/bin/python3.7 ../src/lowlevel/main.py --phase train --experiment_name ex_5_emnist_64_2 --dataset emnist --gpu_ids 0,1 --feature_layer_size 64 --categorical_dim 2 --num_epochs 200
~/miniconda3/envs/mlp/bin/python3.7 ../src/lowlevel/main.py --phase train --experiment_name ex_6_emnist_32_4 --dataset emnist --gpu_ids 0,1 --feature_layer_size 32 --categorical_dim 4 --num_epochs 200
~/miniconda3/envs/mlp/bin/python3.7 ../src/lowlevel/main.py --phase train --experiment_name ex_6_emnist_64_8 --dataset emnist --gpu_ids 0,1 --feature_layer_size 64 --categorical_dim 8 --num_epochs 200
~/miniconda3/envs/mlp/bin/python3.7 ../src/lowlevel/main.py --phase train --experiment_name ex_6_emnist_128_4 --dataset emnist --gpu_ids 0,1 --feature_layer_size 128 --categorical_dim 4 --num_epochs 200
~/miniconda3/envs/mlp/bin/python3.7 ../src/lowlevel/main.py --phase train --experiment_name ex_6_emnist_128_2 --dataset emnist --gpu_ids 0,1 --feature_layer_size 128 --categorical_dim 2 --num_epochs 200
~/miniconda3/envs/mlp/bin/python3.7 ../src/lowlevel/main.py --phase train --experiment_name ex_6_emnist_128_8 --dataset emnist --gpu_ids 0,1 --feature_layer_size 128 --categorical_dim 8 --num_epochs 200
~/miniconda3/envs/mlp/bin/python3.7 ../src/lowlevel/main.py --phase train --experiment_name ex_6_emnist_32_2 --dataset emnist --gpu_ids 0,1 --feature_layer_size 32 --categorical_dim 2 --num_epochs 200
~/miniconda3/envs/mlp/bin/python3.7 ../src/lowlevel/main.py --phase train --experiment_name ex_6_emnist_32_8 --dataset emnist --gpu_ids 0,1 --feature_layer_size 32 --categorical_dim 8 --num_epochs 200